/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 github.gltf
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Github() {
  const { nodes, materials } = useGLTF('/github.gltf')
  return (
    <group dispose={null} scale={4} position={[7.5, 1, -3]}>
      <mesh
        onClick={(e) => {
          e.stopPropagation();
          console.log("click");
          if (e.ctrlKey) {
            window.open("https:/https://github.com/cristianeze16", "_blank");
          }
        }}
        geometry={nodes.Curve.geometry}
        material={materials.SVGMat}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[35.52, 10, 36.43]}
      />
    </group>
  );
}

useGLTF.preload('/github.gltf')
